scopes:

    enabled:

        # Filter name
        label: plus.area::lang.areas.disabled_label

        # Filter type
        type: switch

        # SQL Conditions
        conditions:
            - is_enabled = '1'
            - is_enabled = '0'