list: $/plus/area/models/county/columns.yaml
modelClass: Plus\Area\Models\County
title: Counties
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/area/counties/update/:id'
