list: $/plus/area/models/town/columns.yaml
modelClass: Plus\Area\Models\Town
title: Towns
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/area/towns/update/:id'
