list: $/plus/area/models/city/columns.yaml
modelClass: Plus\Area\Models\City
title: Cities
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/area/cities/update/:id'
